apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
        - name: bookmyshow
          image: 834863651684.dkr.ecr.us-east-1.amazonaws.com/bookmyshow:latest
          ports:
            - containerPort: 3000

