apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - port: 80
      targetPort: 80    # FIXED
      protocol: TCP
